package com.example.githubjetpackcompose.domain.mapper

import com.example.githubjetpackcompose.data.model.DetailsDepotDataJson
import com.example.githubjetpackcompose.data.model.ListReposDataItemJson
import com.example.githubjetpackcompose.data.model.OwnerJson
import com.example.githubjetpackcompose.data.model.UserDataJson
import com.example.githubjetpackcompose.domain.model.DetailsDepotDataModel
import com.example.githubjetpackcompose.domain.model.ListReposDataItemModel
import com.example.githubjetpackcompose.domain.model.OwnerModel
import com.example.githubjetpackcompose.domain.model.UserDataModel
import javax.inject.Inject

class GitMapper @Inject constructor() {

    fun toUserDataModel(json: UserDataJson?): UserDataModel {
        return UserDataModel(
            avatar_url = json?.avatar_url,
            bio = json?.bio,
            blog = json?.blog,
            company = json?.company,
            created_at = json?.created_at,
            email = json?.email,
            events_url = json?.events_url,
            followers = json?.followers ?: 0,
            followers_url = json?.followers_url,
            following = json?.following ?: 0,
            following_url = json?.following_url,
            gists_url = json?.gists_url,
            gravatar_id = json?.gravatar_id,
            hireable = json?.hireable,
            html_url = json?.html_url,
            id = json?.id ?: 0,
            location = json?.location,
            login = json?.login,
            name = json?.name,
            node_id = json?.node_id,
            organizations_url = json?.organizations_url,
            public_gists = json?.public_gists ?: 0,
            public_repos = json?.public_repos ?: 0,
            received_events_url = json?.received_events_url,
            repos_url = json?.repos_url,
            site_admin = json?.site_admin ?: false,
            starred_url = json?.starred_url,
            subscriptions_url = json?.subscriptions_url,
            twitter_username = json?.twitter_username,
            type = json?.type,
            updated_at = json?.updated_at,
            url = json?.url
        )
    }

    fun toOwnerModel(json: OwnerJson?): OwnerModel {
        return OwnerModel(
            avatar_url = json?.avatar_url,
            events_url = json?.events_url,
            followers_url = json?.followers_url,
            following_url = json?.following_url,
            gists_url = json?.gists_url,
            gravatar_id = json?.gravatar_id,
            html_url = json?.html_url,
            id = json?.id ?: 0,
            login = json?.login,
            node_id = json?.node_id,
            organizations_url = json?.organizations_url,
            received_events_url = json?.received_events_url,
            repos_url = json?.repos_url,
            site_admin = json?.site_admin ?: false,
            starred_url = json?.starred_url,
            subscriptions_url = json?.subscriptions_url,
            type = json?.type,
            url = json?.url
        )
    }

    fun toListReposDataItemModel(json: ListReposDataItemJson?): ListReposDataItemModel {
        val ownerModel = toOwnerModel(json?.owner)
        return ListReposDataItemModel(
            allow_forking = json?.allow_forking ?: false,
            archive_url = json?.archive_url,
            archived = json?.archived ?: false,
            assignees_url = json?.assignees_url,
            blobs_url = json?.blobs_url,
            branches_url = json?.branches_url,
            clone_url = json?.clone_url,
            collaborators_url = json?.collaborators_url,
            comments_url = json?.comments_url,
            commits_url = json?.commits_url,
            compare_url = json?.compare_url,
            contents_url = json?.contents_url,
            contributors_url = json?.contributors_url,
            created_at = json?.created_at,
            default_branch = json?.default_branch,
            deployments_url = json?.deployments_url,
            description = json?.description,
            disabled = json?.disabled ?: false,
            downloads_url = json?.downloads_url,
            events_url = json?.events_url,
            fork = json?.fork ?: false,
            forks = json?.forks ?: 0,
            forks_count = json?.forks_count ?: 0,
            forks_url = json?.forks_url,
            full_name = json?.full_name,
            git_commits_url = json?.git_commits_url,
            git_refs_url = json?.git_refs_url,
            git_tags_url = json?.git_tags_url,
            git_url = json?.git_url,
            has_discussions = json?.has_discussions ?: false,
            has_downloads = json?.has_downloads ?: false,
            has_issues = json?.has_issues ?: false,
            has_pages = json?.has_pages ?: false,
            has_projects = json?.has_projects ?: false,
            has_wiki = json?.has_wiki ?: false,
            homepage = json?.homepage,
            hooks_url = json?.hooks_url,
            html_url = json?.html_url,
            id = json?.id ?: 0,
            is_template = json?.is_template ?: false,
            issue_comment_url = json?.issue_comment_url,
            issue_events_url = json?.issue_events_url,
            issues_url = json?.issues_url,
            keys_url = json?.keys_url,
            labels_url = json?.labels_url,
            language = json?.language,
            languages_url = json?.languages_url,
            license = json?.license,
            merges_url = json?.merges_url,
            milestones_url = json?.milestones_url,
            mirror_url = json?.mirror_url,
            name = json?.name,
            node_id = json?.node_id,
            notifications_url = json?.notifications_url,
            open_issues = json?.open_issues ?: 0,
            open_issues_count = json?.open_issues_count ?: 0,
            owner = ownerModel,
            private = json?.private ?: false,
            pulls_url = json?.pulls_url,
            pushed_at = json?.pushed_at,
            releases_url = json?.releases_url,
            size = json?.size ?: 0,
            ssh_url = json?.ssh_url,
            stargazers_count = json?.stargazers_count ?: 0,
            stargazers_url = json?.stargazers_url,
            statuses_url = json?.statuses_url,
            subscribers_url = json?.subscribers_url,
            subscription_url = json?.subscription_url,
            svn_url = json?.svn_url,
            tags_url = json?.tags_url,
            teams_url = json?.teams_url,
            topics = json?.topics ?: emptyList(),
            trees_url = json?.trees_url,
            updated_at = json?.updated_at,
            url = json?.url,
            visibility = json?.visibility,
            watchers = json?.watchers ?: 0,
            watchers_count = json?.watchers_count ?: 0,
            web_commit_signoff_required = json?.web_commit_signoff_required ?: false
        )
    }

    fun toListReposDataItemModel(jsonList: List<ListReposDataItemJson>?): List<ListReposDataItemModel>? {
        return jsonList?.map { toListReposDataItemModel(it) }
    }

    fun toDetailsDepotDataModel(json: DetailsDepotDataJson?): DetailsDepotDataModel {
        val ownerModel = toOwnerModel(json?.owner)
        return DetailsDepotDataModel(
            allow_forking = json?.allow_forking ?: false,
            archive_url = json?.archive_url,
            archived = json?.archived ?: false,
            assignees_url = json?.assignees_url,
            blobs_url = json?.blobs_url,
            branches_url = json?.branches_url,
            clone_url = json?.clone_url,
            collaborators_url = json?.collaborators_url,
            comments_url = json?.comments_url,
            commits_url = json?.commits_url,
            compare_url = json?.compare_url,
            contents_url = json?.contents_url,
            contributors_url = json?.contributors_url,
            created_at = json?.created_at,
            default_branch = json?.default_branch,
            deployments_url = json?.deployments_url,
            description = json?.description,
            disabled = json?.disabled ?: false,
            downloads_url = json?.downloads_url,
            events_url = json?.events_url,
            fork = json?.fork ?: false,
            forks = json?.forks ?: 0,
            forks_count = json?.forks_count ?: 0,
            forks_url = json?.forks_url,
            full_name = json?.full_name,
            git_commits_url = json?.git_commits_url,
            git_refs_url = json?.git_refs_url,
            git_tags_url = json?.git_tags_url,
            git_url = json?.git_url,
            has_discussions = json?.has_discussions ?: false,
            has_downloads = json?.has_downloads ?: false,
            has_issues = json?.has_issues ?: false,
            has_pages = json?.has_pages ?: false,
            has_projects = json?.has_projects ?: false,
            has_wiki = json?.has_wiki ?: false,
            homepage = json?.homepage,
            hooks_url = json?.hooks_url,
            html_url = json?.html_url,
            id = json?.id ?: 0,
            is_template = json?.is_template ?: false,
            issue_comment_url = json?.issue_comment_url,
            issue_events_url = json?.issue_events_url,
            issues_url = json?.issues_url,
            keys_url = json?.keys_url,
            labels_url = json?.labels_url,
            language = json?.language,
            languages_url = json?.languages_url,
            license = json?.license,
            merges_url = json?.merges_url,
            milestones_url = json?.milestones_url,
            mirror_url = json?.mirror_url,
            name = json?.name,
            network_count = json?.network_count ?: 0,
            node_id = json?.node_id,
            notifications_url = json?.notifications_url,
            open_issues = json?.open_issues ?: 0,
            open_issues_count = json?.open_issues_count ?: 0,
            owner = ownerModel,
            private = json?.private ?: false,
            pulls_url = json?.pulls_url,
            pushed_at = json?.pushed_at,
            releases_url = json?.releases_url,
            size = json?.size ?: 0,
            ssh_url = json?.ssh_url,
            stargazers_count = json?.stargazers_count ?: 0,
            stargazers_url = json?.stargazers_url,
            statuses_url = json?.statuses_url,
            subscribers_count = json?.subscribers_count ?: 0,
            subscribers_url = json?.subscribers_url,
            subscription_url = json?.subscription_url,
            svn_url = json?.svn_url,
            tags_url = json?.tags_url,
            teams_url = json?.teams_url,
            temp_clone_token = json?.temp_clone_token,
            topics = json?.topics ?: emptyList(),
            trees_url = json?.trees_url,
            updated_at = json?.updated_at,
            url = json?.url,
            visibility = json?.visibility,
            watchers = json?.watchers ?: 0,
            watchers_count = json?.watchers_count ?: 0,
            web_commit_signoff_required = json?.web_commit_signoff_required ?: false
        )
    }
}
