package com.example.githubjetpackcompose.domain.mapper

import com.example.githubjetpackcompose.data.model.ListReposDataItemJson
import com.example.githubjetpackcompose.domain.model.ListReposDataItemModel

fun ListReposDataItemJson.toDomain(): ListReposDataItemModel {
    return ListReposDataItemModel(
        allow_forking = allow_forking,
        archive_url = archive_url,
        archived = archived,
        assignees_url = assignees_url,
        blobs_url = blobs_url,
        branches_url = branches_url,
        clone_url = clone_url,
        collaborators_url = collaborators_url,
        comments_url = comments_url,
        commits_url = commits_url,
        compare_url = compare_url,
        contents_url = contents_url,
        contributors_url = contributors_url,
        created_at = created_at,
        default_branch = default_branch,
        deployments_url = deployments_url,
        description = description,
        disabled = disabled,
        downloads_url = downloads_url,
        events_url = events_url,
        fork = fork,
        forks = forks,
        forks_count = forks_count,
        forks_url = forks_url,
        full_name = full_name,
        git_commits_url = git_commits_url,
        git_refs_url = git_refs_url,
        git_tags_url = git_tags_url,
        git_url = git_url,
        has_discussions = has_discussions,
        has_downloads = has_downloads,
        has_issues = has_issues,
        has_pages = has_pages,
        has_projects = has_projects,
        has_wiki = has_wiki,
        homepage = homepage,
        hooks_url = hooks_url,
        html_url = html_url,
        id = id,
        is_template = is_template,
        issue_comment_url = issue_comment_url,
        issue_events_url = issue_events_url,
        issues_url = issues_url,
        keys_url = keys_url,
        labels_url = labels_url,
        language = language,
        languages_url = languages_url,
        license = license,
        merges_url = merges_url,
        milestones_url = milestones_url,
        mirror_url = mirror_url,
        name = name,
        node_id = node_id,
        notifications_url = notifications_url,
        open_issues = open_issues,
        open_issues_count = open_issues_count,
        owner = owner.toDomain(),
        private = private,
        pulls_url = pulls_url,
        pushed_at = pushed_at,
        releases_url = releases_url,
        size = size,
        ssh_url = ssh_url,
        stargazers_count = stargazers_count,
        stargazers_url = stargazers_url,
        statuses_url = statuses_url,
        subscribers_url = subscribers_url,
        subscription_url = subscription_url,
        svn_url = svn_url,
        tags_url = tags_url,
        teams_url = teams_url,
        topics = topics,
        trees_url = trees_url,
        updated_at = updated_at,
        url = url,
        visibility = visibility,
        watchers = watchers,
        watchers_count = watchers_count,
        web_commit_signoff_required = web_commit_signoff_required
    )
}

fun List<ListReposDataItemJson>?.toDomain(): List<ListReposDataItemModel>? {
    return this?.map { it.toDomain() }
}
